# https://github.com/judge0/judge0/blob/v1.13.1/judge0.conf
REDIS_HOST=redis
REDIS_PASSWORD=judge0_redis_pass
POSTGRES_HOST=db
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_password
POSTGRES_DB=judge0
